version: "3.8"

services:
  marketplace:
#    build:
#      context: .
#      dockerfile: marketplace/Dockerfile
    environment:
      RECOMMENDATIONS_HOST: recommendations
    image: adalovelace4242/flaskbooks/marketplace
    networks:
      - microservices
    ports:
      - 5000:5000

  recommendations:
#    build:
#      context: .
#      dockerfile: recommendations/Dockerfile
    environment:
      GRPC_PORT: 50051
    image: adalovelace4242/flaskbooks/recommendations
    networks:
      - microservices

networks:
  microservices: